######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 13 17:59:19 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += a.cpp
