######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 13 13:57:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += a.cpp
CONFIG += meegotouch
