######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 13 15:14:48 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += a.cpp
